// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXv5VWJRxNQYiXnXaonMrIokeoGwF7AV8',
    appId: '1:929529357029:web:187be5a9b424876da92a0c',
    messagingSenderId: '929529357029',
    projectId: 'whatsapp-clone-br772',
    authDomain: 'whatsapp-clone-br772.firebaseapp.com',
    storageBucket: 'whatsapp-clone-br772.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4wIAgZ9VtyVXMKasfkVD_qFNdbhxfOy0',
    appId: '1:929529357029:android:2605c1201ac27d69a92a0c',
    messagingSenderId: '929529357029',
    projectId: 'whatsapp-clone-br772',
    storageBucket: 'whatsapp-clone-br772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG29ZCXYCZGPkOpIbCH-WNvh9_Vdov6-I',
    appId: '1:929529357029:ios:1dee1c8f7660b3c1a92a0c',
    messagingSenderId: '929529357029',
    projectId: 'whatsapp-clone-br772',
    storageBucket: 'whatsapp-clone-br772.firebasestorage.app',
    iosBundleId: 'com.custom.whatsapp.clone',
  );

}